# Generated by Django 5.0.2 on 2024-02-19 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplikasi_django_kedua', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
                ('usia', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
